services:
  vector-db:
    image: qdrant/qdrant
    ports:
      - 6333:6333

  graph-db:
    image: neo4j:latest
    ports:
      - "7474:7474" # UI
      - "7687:7687" # Client connection
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/test12345

volumes:
  neo4j_data: